version: "2"
linters:
  default: standard
  enable:
    - testifylint
    - gosec
    - importas
    - modernize
    - testpackage
    - loggercheck
    - sloglint
    - canonicalheader
    - gocritic

  exclusions:
    rules:
      - linters: [errcheck]
        # no need to check defer errors
        source: "^\\s*defer\\s+"
