version: "2"
linters:
  default: standard
  enable:
    - testifylint
    - gosec
    - importas
    - modernize
    - loggercheck
    - sloglint
    - canonicalheader
    - gocritic
    - cyclop
    - revive
    - ineffassign
    - nilnesserr
    - unused
    - thelper
    - errorlint
    - usestdlibvars
    - misspell
  exclusions:
    presets:
      - std-error-handling
    warn-unused: true
  settings:
    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
    gocritic:
      enable-all: true
      disabled-checks:
        - paramTypeCombine # I find it more clear to have explicit types in parameters
formatters:
  enable:
    - gofumpt
    - golines
  settings:
    golines:
      max-len: 120
