version: "2"
linters:
  default: standard
  enable:
    - testifylint
    - gosec
    - importas
    - modernize
    - loggercheck
    - sloglint
    - canonicalheader
    - gocritic
    - cyclop
    - revive

  exclusions:
    rules:
      - linters: [errcheck]
        # no need to check defer errors
        source: "^\\s*defer\\s+"
formatters:
  enable:
    - gofumpt
    - golines  
  settings:
    golines:
      max-len: 120  
